name: Build
on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      runtime_version:
        type: string
        description: 'Version of the runtime to build against'
        required: false
        default: 'v6.0.1'

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        platform: [linux, macos, windows]
        include:
          - platform: linux
            os: ubuntu-latest
          - platform: macos
            os: macos-latest
          - platform: windows
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt -y install build-essential pkg-config libx11-dev libxcursor-dev \
            libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev \
            libudev-dev libxi-dev libxrandr-dev yasm

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python Packages
        run: python -m pip install scons

      - name: Install Windows Python Packages
        if: runner.os == 'Windows'
        shell: bash
        run: python -m pip install pywin32

      - name: MSVC Developer Command Prompt
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build
        run: scons runtime_version=${{ github.event.inputs.runtime_version || 'v6.0.1' }}
